name: "Campbell's English School"
favicon: null
layout_spectrum: 0.24124
typography_spectrum: 0.2596
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Campbell's English School "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e1dc'
    - '#b7b6b1'
    - '#6d7e78'
    - '#0e0e0e'
    - '#4fbddf'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
