name: "Campbell's English School"
favicon: null
layout_spectrum: 0.9975
typography_spectrum: 0.2596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8686aa'
    - '#d3d3d3'
    - '#97d832'
    - '#cc6157'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
