name: "Campbell's English School"
favicon: null
layout_spectrum: 0.9975
typography_spectrum: 0.2596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fdbff'
    - '#408f32'
    - '#7a431d'
    - '#ffe926'
    - '#ea7715'
  brandStrength: 0.4897000358905643
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
