typography_spectrum: 0.108396
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
title: "Campbell's English School "
purpose: []
color:
  saturation: 0.8721805
  brandStrength: 0
  rhythmicContrast: 0.9154136
  brandColors:
    - '#e0e1dc'
    - '#b7b6b1'
    - '#6d7e78'
    - '#0e0e0e'
    - '#4fbddf'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "Campbell's English School"
